### ISSUE TITLE
"CTRL+C + ..." shortcuts blocks copy/paste ...

### ISSUE THREAD

**Issue by MLefebvreICO** [fabiodamasceno/vscode-console-wrapper#5]
I was wondering why I couldn't do `CTRL+C` to copy in VSCode while my coworker it works perfectly fines ... 
Turns out this was this extension that was preventing the `CTRL+C` shortcut for copy.

Please consider changing the default keybinds of the extension.

**Comment by shockthetoast** [comment]
On my system the only keybinding set by this extension is `Ctrl + Shift + Q`. Are you sure this is the extension that is changing your keybinding?

**Comment by MLefebvreICO** [comment]
@shockthetoast I'm pretty sure as this is the only extension I have uninstalled to make my copy/paste works again.

I'll confirm once I can reinstall the extension (Currently VSCode Marketplace is down ..)

**Comment by MLefebvreICO** [comment]
I screw up, though I was installing this extension, but it's another one ...
